# Generated by Django 6.0.4 on 2026-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('hospitals', models.IntegerField(blank=True, null=True)),
                ('health_centres', models.IntegerField(blank=True, null=True)),
                ('primary_schools', models.IntegerField(blank=True, null=True)),
                ('secondary_schools', models.IntegerField(blank=True, null=True)),
                ('povery_index', models.FloatField(blank=True, null=True)),
                ('main_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['code'],
            },
        ),
    ]
