# Generated by Django 6.0.4 on 2026-04-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='povery_index',
            new_name='poverty_index',
        ),
    ]
